services:
  aquascope:
    build:
      context: ./aquascope
      dockerfile: Dockerfile
    container_name: aquascope
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./aquascope/markdowns
        target: /aquascope/src